[project]
name = "humainkind"
version = "0.1.0"
description = "Dynamical systems modeling of the interaction between humankind and artificial intelligence (AI)."
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
    { name = "Simon Altrogge", email = "8720147+simonaltrogge@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "diffrax>=0.7.2",
    "equinox>=0.13.8",
    "jax>=0.11.0",
    "jaxtyping>=0.3.11",
    "marimo>=0.23.16",
    "matplotlib>=3.11.1",
    "optimistix>=0.1.0",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.2",
    "ty>=0.0.70",
]
